import {ALLOWED_GLOBALS, ALLOWED_IMPORTS} from '@kinetiq/domain/allowlist';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';

// Generates packages/primitives/API.md from the code: every building block a
// scene may import, with its props or signature and its source comments. The
// scene-coder prompt includes this file (cached). A test fails if it is stale.

const PRIMITIVES = join(dirname(fileURLToPath(import.meta.url)), '../../../primitives');
export const API_MD = join(PRIMITIVES, 'API.md');

const FLAGS = ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType;

function commentOf(node: ts.Node, text: string): string {
	const ranges = ts.getLeadingCommentRanges(text, node.getFullStart()) ?? [];
	return ranges
		.map((r) => text.slice(r.pos, r.end))
		.map((c) =>
			c
				.replace(/^\/\*\*?|\*\/$/g, '')
				.split('\n')
				.map((line) => line.replace(/^\s*(\/\/|\*)\s?/, '').trimEnd())
				.join('\n')
				.trim(),
		)
		.filter((c) => c && !c.startsWith('eslint') && !c.startsWith('prettier'))
		.join('\n');
}

function statementOf(node: ts.Node): ts.Node {
	let current = node;
	while (current.parent && !ts.isSourceFile(current.parent)) current = current.parent;
	return current;
}

/** For `const X: React.FC<Props>` returns the props type's source text. */
function propsOf(decl: ts.VariableDeclaration): string | null {
	const type = decl.type;
	if (!type || !ts.isTypeReferenceNode(type) || !/(^|\.)FC$/.test(type.typeName.getText())) return null;
	const arg = type.typeArguments?.[0];
	if (!arg) return '{}';
	if (ts.isTypeReferenceNode(arg)) {
		const local = decl.getSourceFile().statements.find(
			(s): s is ts.TypeAliasDeclaration => ts.isTypeAliasDeclaration(s) && s.name.text === arg.typeName.getText(),
		);
		if (local) return local.type.getText();
	}
	return arg.getText();
}

export function generatePrimitivesApi(): string {
	const program = ts.createProgram([join(PRIMITIVES, 'src/index.ts')], {
		jsx: ts.JsxEmit.ReactJSX,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		module: ts.ModuleKind.ESNext,
		target: ts.ScriptTarget.ES2023,
		strict: true,
		skipLibCheck: true,
		noEmit: true,
	});
	const checker = program.getTypeChecker();
	const index = program.getSourceFile(join(PRIMITIVES, 'src/index.ts'))!;
	const exports = checker.getExportsOfModule(checker.getSymbolAtLocation(index)!);
	const allowed = new Set<string>(ALLOWED_IMPORTS['@kinetiq/primitives']);

	const components: string[] = [];
	const helpers: string[] = [];
	const types: string[] = [];

	for (const exported of [...exports].sort((a, b) => a.name.localeCompare(b.name))) {
		const symbol = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
		const decl = symbol.declarations?.[0];
		if (!decl) continue;
		const file = decl.getSourceFile();
		const comment = commentOf(statementOf(decl), file.getFullText());
		const about = comment ? `${comment}\n\n` : '';

		if (ts.isTypeAliasDeclaration(decl)) {
			types.push(`### ${exported.name}\n\n${about}\`\`\`ts\ntype ${exported.name} = ${decl.type.getText()};\n\`\`\`\n`);
			continue;
		}
		if (!allowed.has(exported.name)) continue;
		const props = ts.isVariableDeclaration(decl) ? propsOf(decl) : null;
		if (props !== null) {
			components.push(`### <${exported.name}>\n\n${about}\`\`\`ts\ntype ${exported.name}Props = ${props};\n\`\`\`\n`);
		} else {
			const type = checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, decl), undefined, FLAGS);
			helpers.push(`### ${exported.name}\n\n${about}\`\`\`ts\n${exported.name}: ${type}\n\`\`\`\n`);
		}
	}

	const globals = Object.entries(ALLOWED_GLOBALS)
		.map(([name, rule]) => (rule.members ? `\`${name}.{${rule.members.join(', ')}}\`` : `\`${name}\``))
		.join(', ');

	return `<!-- Generated by \`pnpm --filter @kinetiq/renderer docs:primitives\` from the code. Do not edit. -->
# Kinetiq primitives: API for scene code

Scene code is one TSX module whose \`export default\` is the scene component. It is
validated before it runs (docs/ARCHITECTURE.md §6). What you may use:

- From \`@kinetiq/primitives\`: everything below.
- From \`remotion\`: ${ALLOWED_IMPORTS.remotion.map((n) => `\`${n}\``).join(', ')}.
- From \`react\`: ${ALLOWED_IMPORTS.react.map((n) => `\`${n}\``).join(', ')} (JSX needs no import).
- Globals: ${globals}.

Not allowed: other imports, network, timers, \`window\`/\`document\`, \`obj[x]\` with a
non-literal key (use \`arr.at(i)\`), \`Math.random\` (use remotion's \`random(seed)\`),
classes, \`this\`, async code, \`ref\`, event handlers, \`<img>\`/\`<a>\`/\`<script>\`.
Read the theme with \`useTheme()\`; never hard-code brand colors.

## Components

${components.join('\n')}
## Helpers

${helpers.join('\n')}
## Types

${types.join('\n')}`;
}
